### ISSUE TITLE
Stacktrace is leaked in error response when login failed

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [KMU-Dev/conote#21]
This is the error response of banned user when login:
```json
{
  "errors": [
    {
      "message": "Your account is banned.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "response": {
          "statusCode": 401,
          "message": "Your account is banned."
        },
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [
            "Error: Your account is banned.",
            "    at AuthService.login (D:\\Projects\\compound\\KMU-Dev\\conote\\api\\src\\auth\\auth.service.ts:53:53)",
            "    at target (D:\\Projects\\compound\\KMU-Dev\\conote\\api\\node_modules\\@nestjs\\core\\helpers\\external-context-creator.js:77:28)",
            "    at D:\\Projects\\compound\\KMU-Dev\\conote\\api\\node_modules\\@nestjs\\core\\helpers\\external-proxy.js:9:24"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by ZhaoTzuHsien** [comment]
We can simply pass `debug: false` options to `GraphQLModule` to disable this issue.

`api/src/app.module.ts`
```ts 
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { GraphQLModule } from '@nestjs/graphql';
import { AuthModule } from './auth/auth.module';
import { UserModule } from './user/user.module';
import { PrismaModule } from './prisma/prisma.module';
import { InitModule } from './init/init.module';
import { UiModule } from './ui/ui.module';
import configuration from './config/configuration';
import { CaslModule } from './casl/casl.module';

@Module({
    imports: [
        ConfigModule.forRoot({
            isGlobal: true,
            load: [configuration],
        }),
        GraphQLModule.forRoot({
            debug: false
            autoSchemaFile: true,
            buildSchemaOptions: {
                dateScalarMode: 'timestamp',
            },
            context: ({ req, res }) => ({ req, res }),
        }),
        PrismaModule,
        AuthModule,
        CaslModule,
        UserModule,
        InitModule,
        UiModule,
    ],
})
export class AppModule {}
```
