### ISSUE TITLE
User DataTable cannot get user in last page which only contains one user

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [KMU-Dev/conote#46]
Table last page with only one user cannot show correctly.

**Comment by ZhaoTzuHsien** [comment]
If we sort by status, this issue happens

**Comment by ZhaoTzuHsien** [comment]
Error log:
```
[Nest] 26  - 02/21/2022, 10:12:57 AM   ERROR [ExceptionsHandler] 
Invalid `this.getDelegate().findMany()` invocation in
/app/dist/utils/graphql/crud/abstract-prisma-connection.service.js:17:55

  14     : args.before && this.parseCursor(args.before);
  15 const takeLength = args.first ? args.first + 1 : args.last + 1;
  16 const take = args.first ? takeLength : -takeLength;
→ 17 const entities = await this.getDelegate().findMany({
       where: undefined,
       orderBy: [
         {
           status: 'asc'
         }
       ],
       cursor: NaN,
               ~~~
       take: -11,
       skip: NaN
             ~~~
     })

Argument cursor: Got invalid value NaN on prisma.findManyUser. Provided Float, expected UserWhereUniqueInput:
type UserWhereUniqueInput {
  id?: Int
  email?: String
  studentId?: String
}
Argument skip: Got invalid value NaN on prisma.findManyUser. Provided Float, expected Int.


Error: 
Invalid `this.getDelegate().findMany()` invocation in
/app/dist/utils/graphql/crud/abstract-prisma-connection.service.js:17:55

  14     : args.before && this.parseCursor(args.before);
  15 const takeLength = args.first ? args.first + 1 : args.last + 1;
  16 const take = args.first ? takeLength : -takeLength;
→ 17 const entities = await this.getDelegate().findMany({
       where: undefined,
       orderBy: [
         {
           status: 'asc'
         }
       ],
       cursor: NaN,
               ~~~
       take: -11,
       skip: NaN
             ~~~
     })

Argument cursor: Got invalid value NaN on prisma.findManyUser. Provided Float, expected UserWhereUniqueInput:
type UserWhereUniqueInput {
  id?: Int
  email?: String
  studentId?: String
}
Argument skip: Got invalid value NaN on prisma.findManyUser. Provided Float, expected Int.


    at Object.validate (/app/node_modules/@prisma/client/runtime/index.js:34786:20)
    at PrismaService._executeRequest (/app/node_modules/@prisma/client/runtime/index.js:40911:17)
    at consumer (/app/node_modules/@prisma/client/runtime/index.js:40856:23)
    at /app/node_modules/@prisma/client/runtime/index.js:40860:76
    at runInChildSpan (/app/node_modules/@prisma/client/runtime/index.js:39945:12)
    at /app/node_modules/@prisma/client/runtime/index.js:40860:20
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at PrismaService._request (/app/node_modules/@prisma/client/runtime/index.js:40859:86)
    at /app/node_modules/@prisma/client/runtime/index.js:40190:25
    at _callback (/app/node_modules/@prisma/client/runtime/index.js:39960:52)
```
